-- ######## --
-- # DATA # --
-- ######## --


-- create indexes and materialized views for production


-------------------
-- INDEX PARCELS --
-------------------


-- create GiST index on parcels table, given size (~12k polygon features)
CREATE INDEX parcels_ilmenard_geom_gist_index ON parcels_ilmenard USING GIST (geom);


------------------------------------------
-- MATERIALIZED VIEWS FOR VISUALIZATION --
------------------------------------------
-- create materialized views for silos and parcels, to be used in visualization


-- SILOS --
-- "gid" primary key generated by PostGIS
-- "diameter" original diameter, rounded to 1 decimal place
-- "wide_bin_diameter" closest break point for wide corrugation bins (https://www.brockmfg.com/uploads/pdf/BR_2286_201702_Brock_Non_Stiffened_Storage_Capacities_Fact_Sheet_EM.pdf)
-- "max_volume_bushels" maximum capacity in bushels, given diameter (assumes tallest height associated with that wide corrugation bin diameter)
-- "min_volume_bushels" minimum capacity in bushels, given diameter (assumes shortest height associated with that wide corrugation bin diameter)
-- "owner" agricultural parcel (i.e., farm) owner
-- "geom" silo geometry
create materialized view silos as
with p as
(select owner, st_union(geom) as geom from parcels_ilmenard where farm_acres > 0 group by owner)
select
	s.gid,
	round(diameter, 1) as diameter,
	case
		when 4.0 <= round(diameter, 1) and round(diameter, 1) <= 5.0 then 4.6
		when 5.0 <= round(diameter, 1) and round(diameter, 1) <= 5.9 then 5.5
		when 5.9 <= round(diameter, 1) and round(diameter, 1) <= 6.8 then 6.4
		when 6.8 <= round(diameter, 1) and round(diameter, 1) <= 7.7 then 7.3
		when 7.7 <= round(diameter, 1) and round(diameter, 1) <= 8.6 then 8.2
		when 8.6 <= round(diameter, 1) and round(diameter, 1) <= 9.6 then 9.1
		when 9.6 <= round(diameter, 1) and round(diameter, 1) <= 10.5 then 10.1
		when 10.5 <= round(diameter, 1) and round(diameter, 1) <= 11.9 then 11.0
		when 11.9 <= round(diameter, 1) and round(diameter, 1) <= 13.7 then 12.8
		when 13.7 <= round(diameter, 1) and round(diameter, 1) <= 20.0 then 14.6
	end as wide_bin_diameter,
	case
		when 4.0 <= round(diameter, 1) and round(diameter, 1) <= 5.0 then 4563
		when 5.0 <= round(diameter, 1) and round(diameter, 1) <= 5.9 then 7416
		when 5.9 <= round(diameter, 1) and round(diameter, 1) <= 6.8 then 10174
		when 6.8 <= round(diameter, 1) and round(diameter, 1) <= 7.7 then 13392
		when 7.7 <= round(diameter, 1) and round(diameter, 1) <= 8.6 then 18847
		when 8.6 <= round(diameter, 1) and round(diameter, 1) <= 9.6 then 23429
		when 9.6 <= round(diameter, 1) and round(diameter, 1) <= 10.5 then 28543
		when 10.5 <= round(diameter, 1) and round(diameter, 1) <= 11.9 then 34199
		when 11.9 <= round(diameter, 1) and round(diameter, 1) <= 13.7 then 47174
		when 13.7 <= round(diameter, 1) and round(diameter, 1) <= 20.0 then 62429
	end as max_volume_bushels,
	case
		when 4.0 <= round(diameter, 1) and round(diameter, 1) <= 5.0 then 1841
		when 5.0 <= round(diameter, 1) and round(diameter, 1) <= 5.9 then 2709
		when 5.9 <= round(diameter, 1) and round(diameter, 1) <= 6.8 then 3765
		when 6.8 <= round(diameter, 1) and round(diameter, 1) <= 7.7 then 5020
		when 7.7 <= round(diameter, 1) and round(diameter, 1) <= 8.6 then 6482
		when 8.6 <= round(diameter, 1) and round(diameter, 1) <= 9.6 then 10342
		when 9.6 <= round(diameter, 1) and round(diameter, 1) <= 10.5 then 12706
		when 10.5 <= round(diameter, 1) and round(diameter, 1) <= 11.9 then 15349
		when 11.9 <= round(diameter, 1) and round(diameter, 1) <= 13.7 then 21512
		when 13.7 <= round(diameter, 1) and round(diameter, 1) <= 20.0 then 28907
	end as min_volume_bushels,
	owner,
	s.geom::geometry(MultiPolygon,4326) --specify geometry type + SRS (which avoids specifying source SRS via "-s_srs" when exporting via ogr2ogr)
from silos_ilmenard s, p
where st_contains(p.geom, st_centroid(s.geom)) = 'True';


-- PARCELS --
-- "parcels" materialized view includes:
-- "owner" agricultural parcel (i.e., farm) owner (grouped by owner, on "owner" attribute, i.e., first owner name)
-- "parcel_numbers" string of parcel numbers aggregated for all agricultural parcels with given owner
-- "silo_count" count of all silos that are contained within aggregated agricultural parcels with given owner
-- "max_volume_bushels" maximum capacity in bushels of all silos that are contained within aggregated agricultural parcels with given owner (sum of all max_volume_bushels)
-- "min_volume_bushels" minimum capacity in bushels of all silos that are contained within aggregated agricultural parcels with given owner (sum of all min_volume_bushels)
-- "geom" aggregated (via ST_Union) geometry including all agricultural parcels with given owner (i.e., unified "farm" land with given owner)
create materialized view parcels as
with s as (
	select
		gid,
		round(diameter, 1) as diameter,
		case
			when 4.0 <= round(diameter, 1) and round(diameter, 1) <= 5.0 then 4.6
			when 5.0 <= round(diameter, 1) and round(diameter, 1) <= 5.9 then 5.5
			when 5.9 <= round(diameter, 1) and round(diameter, 1) <= 6.8 then 6.4
			when 6.8 <= round(diameter, 1) and round(diameter, 1) <= 7.7 then 7.3
			when 7.7 <= round(diameter, 1) and round(diameter, 1) <= 8.6 then 8.2
			when 8.6 <= round(diameter, 1) and round(diameter, 1) <= 9.6 then 9.1
			when 9.6 <= round(diameter, 1) and round(diameter, 1) <= 10.5 then 10.1
			when 10.5 <= round(diameter, 1) and round(diameter, 1) <= 11.9 then 11.0
			when 11.9 <= round(diameter, 1) and round(diameter, 1) <= 13.7 then 12.8
			when 13.7 <= round(diameter, 1) and round(diameter, 1) <= 20.0 then 14.6
		end as wide_bin_diameter,
		case
			when 4.0 <= round(diameter, 1) and round(diameter, 1) <= 5.0 then 4563
			when 5.0 <= round(diameter, 1) and round(diameter, 1) <= 5.9 then 7416
			when 5.9 <= round(diameter, 1) and round(diameter, 1) <= 6.8 then 10174
			when 6.8 <= round(diameter, 1) and round(diameter, 1) <= 7.7 then 13392
			when 7.7 <= round(diameter, 1) and round(diameter, 1) <= 8.6 then 18847
			when 8.6 <= round(diameter, 1) and round(diameter, 1) <= 9.6 then 23429
			when 9.6 <= round(diameter, 1) and round(diameter, 1) <= 10.5 then 28543
			when 10.5 <= round(diameter, 1) and round(diameter, 1) <= 11.9 then 34199
			when 11.9 <= round(diameter, 1) and round(diameter, 1) <= 13.7 then 47174
			when 13.7 <= round(diameter, 1) and round(diameter, 1) <= 20.0 then 62429
		end as max_volume_bushels,
		case
			when 4.0 <= round(diameter, 1) and round(diameter, 1) <= 5.0 then 1841
			when 5.0 <= round(diameter, 1) and round(diameter, 1) <= 5.9 then 2709
			when 5.9 <= round(diameter, 1) and round(diameter, 1) <= 6.8 then 3765
			when 6.8 <= round(diameter, 1) and round(diameter, 1) <= 7.7 then 5020
			when 7.7 <= round(diameter, 1) and round(diameter, 1) <= 8.6 then 6482
			when 8.6 <= round(diameter, 1) and round(diameter, 1) <= 9.6 then 10342
			when 9.6 <= round(diameter, 1) and round(diameter, 1) <= 10.5 then 12706
			when 10.5 <= round(diameter, 1) and round(diameter, 1) <= 11.9 then 15349
			when 11.9 <= round(diameter, 1) and round(diameter, 1) <= 13.7 then 21512
			when 13.7 <= round(diameter, 1) and round(diameter, 1) <= 20.0 then 28907
		end as min_volume_bushels,
		geom
	from silos_ilmenard
), p as (
		select
			owner,
			string_agg(parcelnumb, ', ') as parcel_numbers,
			st_union(geom) as geom
		from parcels_ilmenard
		where farm_acres > 0
		group by owner
)
select
	owner,
	parcel_numbers,
	count(*) as silo_count,
	sum(max_volume_bushels) as max_volume_bushels,
	sum(min_volume_bushels) as min_volume_bushels,
	p.geom::geometry(MultiPolygon,4326) --specify geometry type + SRS (which avoids specifying source SRS via "-s_srs" when exporting via ogr2ogr)
from s, p
where st_contains(p.geom, st_centroid(s.geom)) = 'True'
group by owner, parcel_numbers, p.geom;
